name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  validate_release:
    name: Validate Release
    uses: ./.github/workflows/release-validate.yml
    secrets: inherit

  release_github:
    name: GitHub Release
    needs: validate_release
    uses: ./.github/workflows/release-github.yml
    with:
      version: ${{ needs.validate_release.outputs.version }}
    secrets: inherit

  publish_crates:
    name: crates.io Publish
    needs: validate_release
    uses: ./.github/workflows/release-crates.yml
    secrets: inherit

  publish_aur:
    name: AUR Publish
    needs:
      - validate_release
      - release_github
      - publish_crates
    uses: ./.github/workflows/release-aur.yml
    with:
      version: ${{ needs.validate_release.outputs.version }}
    secrets: inherit
